### ISSUE TITLE
Wrapper command fails with "local.properties" - no such file or directory

### ISSUE THREAD

**Issue by SkillsDelivery** [gradle/wrapper-upgrade-gradle-plugin#245]
Hello!

When the wrapper upgrade creates a new PR, the `wrapper` command fails with the following message:
```
* What went wrong:
/home/runner/work/my-wrapper-upgrade/my-wrapper-upgrade/build/git-clones/MyProject/local.properties (No such file or directory)
```
This is happening because my `local.properties` file is NOT tracked in git (and it should NOT be).

Could you provide a way for us to run a small script which could be run after cloning and before `wrapper` command  (or at least a way to create these files empty)?

I actually have multiple `*.properties` files and the `wrapper` command fails for all of them.
The temporary solution was to add empty `*.properties` files but that creates many other problems, every time when I want to do a commit, which are part of the reason why these files should NOT be tracked in git.

Thank you!

**Comment by alextu** [comment]
Hello, can't you just add those properties file to `.gitignore`?

**Comment by SkillsDelivery** [comment]
@alextu are you part of the plugin's development team?

**Comment by SkillsDelivery** [comment]
@alextu I could see you are then let me explain:
I wrote "...my local.properties file is NOT tracked in git..." which means it is in .gitignore.
When `./gradlew upgradeGradleWrapperMyPrj` command is executed, it will clone project MyPrj which does not have local.properties file since is not in git (due to being added to .gitignore).
After that the command `./gradlew wrapper --gradle-version=<latest_gradle_version>` will run in the cloned repo. This comand will fail because it will do a gradle sync first, which requires local.properties to be present.
In my worflows I am running a small script which is creating the local.properies file just before running any gradle command.

**Comment by StefMa** [comment]
I am using this plugin on at least 4 Android projects without any problems.
A "Gradle sync" is not a concept of Gradle itself but by IntelliJ and the Gradle integration.
Gradle of course runs a configuration phase of your project. If your project requires at this time a local.properties file you might see this error. 

The problem might not be because of the plugin nor should it provide some hook/action to do  something before it got executed (IMHO). Rather you should check and adjust your project that it doesn't require a local.properties file at configuration phase.

Does this make sense?

**Comment by SkillsDelivery** [comment]
@StefMa in those 4 Android projects, do you have the local.properties pushed (tracked) in the git repository?

**Comment by StefMa** [comment]
Of course the local.properties file is not committed in those.
You can check https://github.com/ioki-mobility/TextRef together with that project https://github.com/ioki-mobility/GradleWrapperUpgrader

The first one is an android project while the second one uses this plugin.
Don't be confused that this lifes in another repo, it's just because the plugin is outside of the main project. But literally it doesn't matter where it is. It also works if directly added to the android project.

You have to check yourself which (maybe) custom task requires the local.properties to be available. Without sharing your project it is hard to help for me.

**Comment by SkillsDelivery** [comment]
Thank you @StefMa for the hints and for the links to the repositories. Your answer pushed me to dig more where is that problem coming from and I found the reason and the proper way to fix it.
So I will close this ticket since it is not valid anymore.

Thanks a lot guys! <3
