### ISSUE TITLE
Wrapper Upgrade Github Action

### ISSUE THREAD

**Issue by cech12** [gradle/wrapper-upgrade-gradle-plugin#30]
I would love to see a Github Action for upgrading Gradle Wrapper which is official maintained by Gradle. (like your [wrapper-validation-action](https://github.com/gradle/wrapper-validation-action))
That would make the update process more efficient. :)

**Comment by etiennestuder** [comment]
This plugin is officially maintained by Gradle.

What would be more efficient in upgrading the Gradle wrapper if there were a GH action?

**Comment by cech12** [comment]
If I want to integrate this plugin in all my projects, I would have to configure the corresponding repository in each project individually by defining the correct Github repository. Additionally I need to define a Github Action that runs the plugin.

While having an action here would have the advantage that I could put the same GH action in any project. Nothing more. :)

**Comment by etiennestuder** [comment]
Thanks for the insights, @cech12 . What we do internally at Gradle, is that we have a private repo in which we configure multiple projects that all have a wrapper to be updated. It means we can configure all repos to update in one place/repo. We only do it differently for our public repos, in order to demonstrate how one can make use of this plugin via GH action.

I understand that having a GH action would provide additional convenience when wanting to upgrade wrappers from GH actions.
